version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app
    env_file: ./.env

  app:
    image: node:current-alpine3.15
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    links:
      - mysql
      - redis
    ports:
      - "5000:5000"
    #entrypoint: /bin/bash
    command: node api/app.js
    #command: bash ping google.com.ar
    env_file: ./.env
    environment:
      "NODE_ENV": "development"

  mysql:
    env_file: ./.env
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_ROOT_PASSWORD}"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

